<a href="https://colab.research.google.com/github/R46a/Generative-AI-2303A52277/blob/main/GAI_7_1_ASS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
# Import necessary libraries
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adadelta
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import joblib


In [4]:
# Load dataset (replace 'data.csv' with your dataset)
data = pd.read_csv('/content/diabetes (1).csv')
data.head()



Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [13]:
data['Pregnancies'] = encoder.fit_transform(data['Pregnancies'])
data['Glucose'] = encoder.fit_transform(data['Glucose'])
data['BloodPressure'] = encoder.fit_transform(data['BloodPressure'])
data['SkinThickness'] = encoder.fit_transform(data['SkinThickness'])
data['Insulin'] = encoder.fit_transform(data['Insulin'])
data['BMI'] = encoder.fit_transform(data['BMI'])


In [14]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            6       86             22             28        0  123   
1            1       23             19             22        0   62   
2            8      121             17              0        0   30   
3            1       27             19             16       62   77   
4            0       75              4             28      102  209   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [21]:
# Define features and target
X = data.drop('Age', axis=1)
y = data['Age']

# Scale the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [22]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
# Define the model
model = Sequential([
    Dense(8, activation='relu', input_dim=X_train.shape[1]),
    Dense(16, activation='relu'),
    Dense(20, activation='relu'),
    Dense(10, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer=Adadelta(),
              loss='mean_squared_error',
              metrics=['mse'])

# Train the model
model.fit(X_train, y_train, epochs=150, batch_size=64)

# Evaluate the model
loss, accuracy = model.evaluate(X_train, y_train, verbose=0)
print(f"Training Loss: {loss:.4f}, Training Accuracy: {accuracy:.4f}")

Epoch 1/150


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 1209.2645 - mse: 1209.2645
Epoch 2/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1163.3708 - mse: 1163.3708 
Epoch 3/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1217.5762 - mse: 1217.5762 
Epoch 4/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1197.9738 - mse: 1197.9738 
Epoch 5/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1195.1842 - mse: 1195.1842 
Epoch 6/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1202.4843 - mse: 1202.4843 
Epoch 7/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1214.6035 - mse: 1214.6035 
Epoch 8/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1235.6871 - mse: 1235.6871 
Epoch 9/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1178.5815 - mse: 1178.5815 
Epoch 10/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1237.6084 - mse: 1237.6084 
Epoch 11/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1180.3429 - mse: 1180.3429 
Epoch 12/150
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - 

In [24]:
# Predictions
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate Mean Squared Error
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)

print(f'Training MSE: {train_mse}')
print(f'Testing MSE: {test_mse}')

20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 
Training MSE: 1180.0828857421875
Testing MSE: 1318.651611328125


In [31]:
# Build confusion matrix
conf_matrix = confusion_matrix(y_test, y_test_pred.round())
print("Confusion Matrix:")
print(conf_matrix)

# Calculate recall, precision, and F1-score
print("\nClassification Report:")
print(classification_report(y_test, y_test_pred.round()))

Confusion Matrix:
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0 12  0 ...  0  0  0]
 ...
 [ 1  1  0 ...  0  0  0]
 [ 1  1  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00       0.0
         1.0       0.00      0.00      0.00       0.0
        21.0       0.00      0.00      0.00      12.0
        22.0       0.00      0.00      0.00      13.0
        23.0       0.00      0.00      0.00       7.0
        24.0       0.00      0.00      0.00      10.0
        25.0       0.00      0.00      0.00       8.0
        26.0       0.00      0.00      0.00       3.0
        27.0       0.00      0.00      0.00       5.0
        28.0       0.00      0.00      0.00       9.0
        29.0       0.00      0.00      0.00      10.0
        30.0       0.00      0.00      0.00       4.0
        31.0       0.00      0.00      0.00       3.0
        32.0       0.00      0.00      0.00  

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

In [36]:
model.save('diabetes_model.h5')

In [37]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [39]:
from tensorflow.keras.models import load_model

# Load the model
loaded_model = load_model('/content/diabetes_model.h5')

# Prepare new data, ensure it has the same features as the training data
new_data = pd.DataFrame([{
    'Pregnancies': 4,
    'Glucose': 160,
    'BloodPressure': 55,
    'SkinThickness': 28,
    'Insulin': 420,
    'BMI': 26.5,
    'DiabetesPedigreeFunction': 0.443,
    'Outcome': 0 # Include 'Outcome'
}])

# Drop 'Age' from new data as it was not used in training
new_data = new_data.drop(columns=['Age'], errors='ignore')  # 'errors='ignore'' handles cases where 'Age' is not present

# Standardize the new data
new_data_scaled = scaler.transform(new_data)

# Predict using the loaded model
prediction = loaded_model.predict(new_data_scaled)
print(f'Predicted Housing Price: {prediction[0][0]}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
Predicted Housing Price: 0.9064611196517944


In [40]:
prediction

array([[0.9064611]], dtype=float32)